#!/bin/sh
# 首次启动切换主题和界面语言；保留网络和登录设置。
uci -q get luci.main >/dev/null || exit 1
uci set luci.main.lang='zh_cn' || exit 1
uci set luci.main.mediaurlbase='/luci-static/argon' || exit 1
uci commit luci || exit 1
exit 0
